# Generated by Django 5.1.1 on 2024-10-09 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Маршрут согласования',
                'verbose_name_plural': 'Маршруты согласования',
            },
        ),
        migrations.CreateModel(
            name='ApproveStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тема согласования')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('order_number', models.IntegerField(verbose_name='Порядковый номер')),
                ('approval_type', models.CharField(choices=[('specific', 'Конкретный'), ('manager', 'Начальник'), ('group', 'Группа')], max_length=10, verbose_name='Тип согласования')),
                ('group_approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Группа')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasker.approvalroute', verbose_name='Маршрут согласования')),
                ('specific_approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Согласователь')),
            ],
            options={
                'verbose_name': 'Шаг согласования',
                'verbose_name_plural': 'Шаги согласования',
                'ordering': ['order_number'],
            },
        ),
    ]
