# Generated by Django 5.1.1 on 2024-10-09 07:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvestep',
            name='description',
        ),
        migrations.AddField(
            model_name='approvestep',
            name='dedlin',
            field=models.DurationField(blank=True, default=datetime.timedelta(days=3), null=True, verbose_name='Срок выполнения задачи'),
        ),
        migrations.AlterField(
            model_name='approvestep',
            name='group_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='approvestep',
            name='specific_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Согласователь'),
        ),
    ]
