# Generated by Django 5.1.1 on 2024-10-09 09:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0002_remove_approvestep_description_approvestep_dedlin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('dedline', models.DurationField(blank=True, default=datetime.timedelta(days=1), null=True, verbose_name='Срок выполнения задачи')),
                ('complexity', models.CharField(choices=[('low', 'Низкая'), ('med', 'Средняя'), ('hig', 'Высокая')], max_length=3, verbose_name='Сложность')),
            ],
            options={
                'verbose_name': 'Шаблон задачи',
                'verbose_name_plural': 'Шаблоны задач',
            },
        ),
        migrations.AlterField(
            model_name='approvestep',
            name='dedlin',
            field=models.DurationField(blank=True, default=datetime.timedelta(days=1), null=True, verbose_name='Срок выполнения задачи'),
        ),
        migrations.CreateModel(
            name='RequestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/request/', verbose_name='Изображение')),
                ('dedline', models.DurationField(blank=True, default=datetime.timedelta(days=3), null=True, verbose_name='Срок выполнения задачи')),
                ('complexity', models.CharField(choices=[('low', 'Низкая'), ('med', 'Средняя'), ('hig', 'Высокая')], max_length=3, verbose_name='Сложность')),
                ('approval_route', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasker.approvalroute', verbose_name='Маршрут согласования')),
            ],
            options={
                'verbose_name': 'Шаблон заявки',
                'verbose_name_plural': 'Шаблоны заявок',
            },
        ),
        migrations.CreateModel(
            name='RequestTaskRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дополнительная информация')),
                ('request_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasker.requesttemplate')),
                ('task_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasker.tasktemplate')),
            ],
            options={
                'unique_together': {('request_template', 'task_template')},
            },
        ),
        migrations.AddField(
            model_name='requesttemplate',
            name='tasks',
            field=models.ManyToManyField(blank=True, through='tasker.RequestTaskRelation', to='tasker.tasktemplate', verbose_name='Задачи'),
        ),
    ]
