# Generated by Django 5.1.1 on 2024-10-10 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasker', '0004_alter_approvestep_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttemplate',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Группа'),
        ),
    ]
