# Generated by Django 5.1.1 on 2024-10-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0008_task_group_comment_unique_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approve',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('prg', 'В работе'), ('aprv', 'Согласованный'), ('cans', 'Отменен'), ('clos', 'Откланен')], default='new', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('prg', 'В работе'), ('aprv', 'Согласование'), ('cans', 'Отменен'), ('clos', 'Отклонен'), ('chk', 'Проверяет пользователь'), ('end', 'Завершен')], default='new', max_length=10, verbose_name='Статус'),
        ),
    ]
