# Generated by Django 5.1.1 on 2024-10-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0009_alter_approve_status_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='approve',
            name='order_number',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Порядковый номер'),
        ),
    ]
