# Generated by Django 5.1.1 on 2024-10-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0013_alter_task_dedlin_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasktemplate',
            old_name='dedline',
            new_name='dedlin',
        ),
    ]
