# Generated by Django 5.1.1 on 2024-10-30 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasker', '0015_alter_requesttemplate_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approve',
            options={'ordering': ['order_number'], 'verbose_name': 'Согласование', 'verbose_name_plural': 'Согласования'},
        ),
        migrations.AddField(
            model_name='approve',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='request',
            name='dedlin_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок выполнения'),
        ),
    ]
