# Generated by Django 5.1.1 on 2024-10-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0016_alter_approve_options_approve_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requesttemplate',
            old_name='dedline',
            new_name='dedlin',
        ),
    ]
