# Generated by Django 5.1.1 on 2025-01-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0017_rename_dedline_requesttemplate_dedlin'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='complexity',
            field=models.CharField(choices=[('low', 'Низкая'), ('med', 'Средняя'), ('hig', 'Высокая')], default='med', max_length=3, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='request',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('med', 'Средний'), ('hig', 'Высокий')], default='med', max_length=3, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='requesttemplate',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('med', 'Средний'), ('hig', 'Высокий')], default='med', max_length=3, verbose_name='Приоритет'),
        ),
    ]
