# Generated by Django 5.1.1 on 2024-10-09 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0003_tasktemplate_alter_approvestep_dedlin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvestep',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tasker.approvalroute', verbose_name='Маршрут согласования'),
        ),
    ]
