# Generated by Django 5.1.1 on 2024-10-10 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasker', '0006_alter_requesttemplate_tasks_comment_request_approve_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requesttaskrelation',
            options={'verbose_name': 'Задача шаблона заявки', 'verbose_name_plural': 'Задачи шаблона заявки'},
        ),
        migrations.AddField(
            model_name='request',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='approve',
            name='coordinating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinating_approve', to=settings.AUTH_USER_MODEL, verbose_name='Согласователь'),
        ),
        migrations.AlterField(
            model_name='approve',
            name='on_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approves', to='tasker.request', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='approve',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('aprv', 'Согласованный'), ('cans', 'Отменен'), ('clos', 'Откланен')], default='new', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='requesttaskrelation',
            name='task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasker.tasktemplate', verbose_name='Шаблон задачи'),
        ),
        migrations.AlterField(
            model_name='requesttemplate',
            name='tasks',
            field=models.ManyToManyField(blank=True, default=None, through='tasker.RequestTaskRelation', to='tasker.tasktemplate', verbose_name='Задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='on_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasker.request', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('prg', 'В работе'), ('aprv', 'Согласование'), ('cans', 'Отменен'), ('clos', 'Откланен'), ('chk', 'Проверяет пользователь'), ('end', 'Завершен')], default='new', max_length=10, verbose_name='Статус'),
        ),
    ]
