# Generated by Django 5.1.1 on 2024-10-21 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasker', '0010_approve_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='task',
            name='on_request',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasker.request', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasker.tasktemplate', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='complexity',
            field=models.CharField(blank=True, choices=[('low', 'Низкая'), ('med', 'Средняя'), ('hig', 'Высокая')], default='med', max_length=3, verbose_name='Сложность'),
        ),
    ]
