# Generated by Django 5.1.1 on 2024-10-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0012_alter_task_dedlin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dedlin_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок выполнения'),
        ),
    ]
